Feature/hw3
katyamichal/ShiftHomeworks pull request #3
Opened 2024-04-29 09:16 UTC by katyamichal

Создала приложение с  UITabBarController c тремя экранами: первый экран сделан через сториборд, второй и третий с помощью anchors.  На всех экран три или более ui элементов.

2024-05-01 09:17 UTC, rmaximov requested changes
Обрати внимание на историю коммитов - не стоит лить всё одним
HW2 pr аппрувнут, можешь вливать
Есть некоторые замечания, не совсем критичные

2024-05-01 09:17 UTC, rmaximov commented on hw1/hw1/App/Main.swift
> -import Foundation
а почему 1 домашка удалена?

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/BioModule/Bio.swift
> +       let myBirthday = Calendar.current.date(from: DateComponents(year: SelfPresentationStrings.BirthDate.year, month: SelfPresentationStrings.BirthDate.month, day: SelfPresentationStrings.BirthDate
минор: в одну строку тяжело читаемо, можно разбить каждый параметр на новой строке

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/BioModule/Bio.swift
> +       let myBirthday = Calendar.current.date(from: DateComponents(year: SelfPresentationStrings.BirthDate.year, month: SelfPresentationStrings.BirthDate.month, day: SelfPresentationStrings.BirthDate
не минор: force unwrap лучше не использовать и значение попытаться развернуть, иначе можно поймать краш

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/Helpers/SelfPresentationStrings.swift
> +enum SelfPresentationStrings {
хороший вынос констант

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +    required init?(coder: NSCoder) {
для таких методов, особенно инитов, можно закрыть доступ к использованию https://www.avanderlee.com/swift/available-deprecated-renamed/

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +        label.font = UIFont(name: "Avenir Next Regular", size: 23)
шрифт повторяется, но меняется размер. Скорей всего можно вынести в отдельную сущность/константу

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbyView.swift
> +        scrollView.frame = CGRect(x: .zero, y: .zero, width: Layout.width, height: Layout.height / 1.3)
хоть 1.3 и встречается один раз, но стоит объявить константой, прям в этом методе, чтобы было понимание откуда взялся коэффициент

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbyView.swift
> +        scrollView.setContentOffset(CGPoint(x: current * (window?.frame.size.width ?? 100), y: 0), animated: true)
давай избавимся от таких длинных арифметических выражений и как-то их назовем

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbyView.swift
> +            pageControl.currentPage = Int(floorf(Float(scrollView.contentOffset.x) / Float(scrollView.frame.size.width)))
а если scrollView.frame.size.width будет 0?

2024-05-01 09:17 UTC, rmaximov commented on hw3/hw3/TabBarViewController.swift
> +    private lazy var techSkillsViewController: TechSckillsViewController = {
минор: можно сократить запись `private lazy var techSkillsViewController =  TechSckillsViewController()`

2024-05-02 09:14 UTC, katyamichal commented on hw1/hw1/App/Main.swift
> -import Foundation
первую домашку добавила
вторую домашку смерджила

2024-05-02 09:17 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +        label.font = UIFont(name: "Avenir Next Regular", size: 23)
исправила: вынесла в отдельную константу

2024-05-02 09:17 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +    required init?(coder: NSCoder) {
исправила везде, где есть init(coder:)

2024-05-02 09:18 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbyView.swift
> +        scrollView.frame = CGRect(x: .zero, y: .zero, width: Layout.width, height: Layout.height / 1.3)
исправила: вынесла в отдельную константу

2024-05-02 09:19 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbyView.swift
> +        scrollView.setContentOffset(CGPoint(x: current * (window?.frame.size.width ?? 100), y: 0), animated: true)
исправила: добавила константу newContentOffsetX для арифметического выражения

2024-05-02 09:20 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbyView.swift
> +            pageControl.currentPage = Int(floorf(Float(scrollView.contentOffset.x) / Float(scrollView.frame.size.width)))
исправила

2024-05-02 09:25 UTC, katyamichal commented on hw3/hw3/BioModule/Bio.swift
> +       let myBirthday = Calendar.current.date(from: DateComponents(year: SelfPresentationStrings.BirthDate.year, month: SelfPresentationStrings.BirthDate.month, day: SelfPresentationStrings.BirthDate
исправила: вынесла DateComponents в отдельную константу
исправила force unwrap: использовала coalescing operator для установки значения по умолчанию

2024-05-02 11:09 UTC, rmaximov commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +        label.font = UIFont(name: "Avenir Next Regular", size: 23)
имел в виду, вынос всего шрифта, например 
`static let avenir23 = UIFont(name: "Avenir Next Regular", size: 23)`

2024-05-02 12:57 UTC, katyamichal commented on hw3/hw3/HobbyModule/HobbySingleView.swift
> +        label.font = UIFont(name: "Avenir Next Regular", size: 23)
исправила: добавила enum для шрифтов

2024-05-02 12:57 UTC, katyamichal commented on hw3/hw3/TabBarViewController.swift
> +    private lazy var techSkillsViewController: TechSckillsViewController = {
исправила

2024-05-02 13:11 UTC, rmaximov approved these changes

2024-05-02 13:26 UTC, merged