Feature/homework4
katyamichal/ShiftHomeworks pull request #4
Opened 2024-05-06 08:48 UTC by katyamichal

1. Экран списка птиц:
   - Использую Collection View для отображения картинки и названия каждой птицы.
   - Для управления данными использую Diffable Data Source.

2.  Экран детальной информации:
   - Использую Collection View для отображения подробной информации о выбранной птице.
   - Для управления данными использую стандартный DataSource.

3.  Для доступа к этому экрану использую кнопку rightBarButtonItem, где можно просмотреть информацию о природоохранном статусе выбранной птицы. Экран отображает цветовую индикацию статуса.

2024-05-06 13:28 UTC, rmaximov requested changes
Обрати внимание на чистоту кода - где-то пробелы лишние и на форс касты

отмечу - разбиение по коммитам и свой код стайл

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    lazy var birdName = bird.name
а для чего переменные lazy и var?

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    private var birdInfo: [String] {
не увидел мутации этого массива, нужен ли тут var?

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailView.swift
> +    lazy var collectionView: UICollectionView = {
нельзя ли сделать приватным это свойство?

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailView.swift
> +    func createBirdimageLayout(isWide: Bool) -> NSCollectionLayoutSection {
минор: image с большой буквы

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailViewController.swift
> +        self.view = BirdDetailView()
где-то self используешь, где-то нет

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailViewController.swift
> +    // MARK: - Methods
минор: название секции в марке не самое говорящее

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/Cells/BirdInfoCell.swift
> +class BirdInfoCell: UICollectionViewCell {
у BirdImageCell указан модификатор final, а здесь нет. Будем наследоваться?

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdListModule/BirdListCollectionViewDataSource.swift
> +final class BirdListCollectionViewDataSource {
класс больше похож не на датасорс, а какой-то конфигуратор датасорса. Тут единственный метод который устаналивает датасорс. Кажется этот класс можно разделить на 2: конфигурация датасорса и какой-то репозиторий с данными

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/Cells/BirdImageCell.swift
> +    func update(imageName: String) {
updateImage?

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdListModule/BirdListCollectionViewDataSource.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BirdCollectionViewCell.reuseIdentifier, for: indexPath) as! BirdCollectionViewCell
форс каст затесался, стоит избавиться

2024-05-06 13:28 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdListModule/Cell/BirdCollectionViewCell.swift
> +    func update(name: String, imageName: String) {
было хорошо, если бы это были 2 разных метода. Тогда мы сможем менять название и картинки независимо друг от друга

2024-05-06 14:31 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    private var birdInfo: [String] {
birdInfo вычисляемая переменная, я не могу сделать ее let

2024-05-06 14:36 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    lazy var birdName = bird.name
я использую birdName для navigation bar tittle, до инициализации проперти bird делаю birdName lazy var

2024-05-08 08:55 UTC, rmaximov commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    lazy var birdName = bird.name
тогда стоит унести отсюда birdName, т.к. класс отвечает за работу с коллекцией. Для navbar нужно отдельно что-то сделать

2024-05-08 12:08 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailCollectionDataSource.swift
> +    lazy var birdName = bird.name
исправила

2024-05-08 12:08 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailView.swift
> +    lazy var collectionView: UICollectionView = {
исправила

2024-05-08 12:08 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/BirdDetailView.swift
> +    func createBirdimageLayout(isWide: Bool) -> NSCollectionLayoutSection {
исправила

2024-05-08 12:15 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/Cells/BirdInfoCell.swift
> +class BirdInfoCell: UICollectionViewCell {
исправила

2024-05-08 12:15 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdListModule/BirdListCollectionViewDataSource.swift
> +final class BirdListCollectionViewDataSource {
исправила

2024-05-08 12:15 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdDetailModule/Cells/BirdImageCell.swift
> +    func update(imageName: String) {
исправила

2024-05-08 12:16 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdListModule/BirdListCollectionViewDataSource.swift
> +            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BirdCollectionViewCell.reuseIdentifier, for: indexPath) as! BirdCollectionViewCell
исправила

2024-05-08 12:16 UTC, katyamichal commented on CollectionApp/CollectionApp/BirdListModule/Cell/BirdCollectionViewCell.swift
> +    func update(name: String, imageName: String) {
исправила

2024-05-11 13:56 UTC, rmaximov approved these changes

2024-05-12 05:30 UTC, merged