Feature/homework7
katyamichal/ShiftHomeworks pull request #7
Opened 2024-06-04 07:26 UTC by katyamichal

**Приложение ImageApp состоит из одного экрана:**
SearchBar и UITableView, в которую загружаются изображение по введенному пользователем названию картинки.

Фунциональность:

- Пользователь вводит название картинки в строку поиска, в случае если строка пустая, показывается алерт.
- При успешной загрузке полученное изображение добавляется в таблицу.
- Если пользователь сворачивает приложение – загрузка продолжается.

Дополнительный функционал:
- Пользователь видит в ячейке сообщение о готовности к загрузке картинки.
- При загрузке картинки отображается прогресс.
- Пользователь может проводить несколько параллельных загрузок одновременно.
- Во время загрузки картинки можно приостановить и затем возобновить с сохранением прогресса.
- При неудачной загрузке пользователь видит сообщение об ошибке.
- Пользователь может удалить ячейки при свайпе вправо после загрузки или при выводе сообщения об ошибке.
- Картинки кэшируются.

2024-06-11 17:10 UTC, rmaximov requested changes
Не получилось тормознуть запрос - кнопка отмены резко появляется и исчезает

В целом хорошая работа, посмотри на объединение нескольких guard в один
Классно что поработала с типом подключения сети, NSCache

2024-06-11 17:10 UTC, rmaximov commented on ImageApp/ImageApp/App/AppDelegate.swift
> +        // Called when the user discards a scene session.
ненужный код

2024-06-11 17:10 UTC, rmaximov commented on ImageApp/ImageApp/ImageListModule/ImageListPresenter.swift
> +    func loadData(with keyword: String) {
в методе нарушен SRP, тут должна быть загрузка, но так же происходит кэширование и обновление ui

2024-06-11 17:10 UTC, rmaximov commented on ImageApp/ImageApp/ImageListModule/ImageListPresenter.swift
> +                guard let index = self.viewData.firstIndex(where: { $0.imageID == imageId }) else { return }
может вытащить это из DispatchQueue.main.async?

2024-06-11 17:10 UTC, rmaximov commented on ImageApp/ImageApp/Services/ImageService/ImageService.swift
> +        guard let pausedTask = tasks[id] else { return }
можно объеденить с guard выше

2024-06-19 10:14 UTC, katyamichal commented on ImageApp/ImageApp/App/AppDelegate.swift
> +        // Called when the user discards a scene session.
удалила

2024-06-19 10:15 UTC, katyamichal commented on ImageApp/ImageApp/ImageListModule/ImageListPresenter.swift
> +    func loadData(with keyword: String) {
разделила на насколько методов, сделала небольшой пин-понг между презентером и вью

2024-06-19 10:15 UTC, katyamichal commented on ImageApp/ImageApp/ImageListModule/ImageListPresenter.swift
> +                guard let index = self.viewData.firstIndex(where: { $0.imageID == imageId }) else { return }
оставила в DispatchQueue.main.async только обновление view

2024-06-19 10:16 UTC, katyamichal commented on ImageApp/ImageApp/Services/ImageService/ImageService.swift
> +        guard let pausedTask = tasks[id] else { return }
поправила везде, где встречалось

2024-06-19 10:20 UTC, katyamichal commented
Проверила еще раз приостановку/возобновление загрузки, все работает.
я тестила с network link conditioner, конкретно этот скрин тест на 3G.
Могу предположить, что у тебя очень быстрый интернет, а картинка легковесная)

https://github.com/katyamichal/ShiftHomeworks/assets/124366801/61621e07-ae62-4836-9d0c-bfd7b7a09a62

PS сорри, что так долго

2024-06-19 10:53 UTC, rmaximov approved these changes

2024-06-19 11:00 UTC, merged